### ISSUE TITLE
Feature Request: Extending Search for Unicode-Code(point)

### ISSUE THREAD

**Issue by AtrusRiven** [BambusControl/obsidian-unicode-search#3]
Thanks for the great Plugin!

For usability purposes I suggest an extension/feature: It would be great if one could not only search for the "name" (e.g. "Right-Pointing Double Angle Quotation Mark" for "»") of the Unicode character but also for the Unicode code(point) itself (e.g. "00BB" for "»").

Would that be a usecase you could consider? Thanks a lot!

**Comment by BambusControl** [comment]
Thanks for the suggestion.
Seems like a logical thing to have… I don't know when I'll get to it—still have something else in the works.

**Comment by BambusControl** [comment]
Implemented in [Release 0.5.0](https://github.com/BambusControl/obsidian-unicode-search/releases/tag/0.5.0)

**Comment by AtrusRiven** [comment]
Thank you very much!
