### ISSUE TITLE
How do I search cuneiform signs?

### ISSUE THREAD

**Issue by Txikivasco** [BambusControl/obsidian-unicode-search#5]
I've tried to type de unicode code point and the primary transliteration in the search bar, but no results show up. IS there a special way to search them?

In case someone wants to have a look at their unicode block, here is the link https://en.wikipedia.org/wiki/Cuneiform_(Unicode_block)

**Comment by BambusControl** [comment]
Not all characters are currently provided, as stated in #4. Closing this issue.
